/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author pc
 */
public class MainFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpnView = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        panelMenu = new javax.swing.JPanel();
        panelMenber = new javax.swing.JPanel();
        jLabelMenber = new javax.swing.JLabel();
        panelDevice = new javax.swing.JPanel();
        jLabelDevice = new javax.swing.JLabel();
        panelViolation = new javax.swing.JPanel();
        jLabelViolation = new javax.swing.JLabel();
        panelAnalytics = new javax.swing.JPanel();
        jLabelAnalytics = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        jpnView.setBackground(new java.awt.Color(223, 223, 223));
        jpnView.setForeground(new java.awt.Color(36, 140, 190));
        jpnView.setPreferredSize(new java.awt.Dimension(909, 566));
        jpnView.setRequestFocusEnabled(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(703, 700));
        jPanel1.setRequestFocusEnabled(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 703, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        panelMenu.setBackground(new java.awt.Color(36, 140, 190));
        panelMenu.setPreferredSize(new java.awt.Dimension(200, 500));

        panelMenber.setBackground(new java.awt.Color(36, 140, 190));
        panelMenber.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        panelMenber.setPreferredSize(new java.awt.Dimension(187, 64));

        jLabelMenber.setBackground(new java.awt.Color(36, 140, 190));
        jLabelMenber.setFont(new java.awt.Font("Times New Roman", 1, 15)); // NOI18N
        jLabelMenber.setForeground(new java.awt.Color(255, 255, 255));
        jLabelMenber.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelMenber.setText("Quản lý thành viên");

        javax.swing.GroupLayout panelMenberLayout = new javax.swing.GroupLayout(panelMenber);
        panelMenber.setLayout(panelMenberLayout);
        panelMenberLayout.setHorizontalGroup(
            panelMenberLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelMenberLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabelMenber, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        panelMenberLayout.setVerticalGroup(
            panelMenberLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMenberLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelMenber, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                .addContainerGap())
        );

        panelDevice.setBackground(new java.awt.Color(36, 140, 190));
        panelDevice.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        panelDevice.setForeground(new java.awt.Color(255, 255, 255));
        panelDevice.setPreferredSize(new java.awt.Dimension(187, 65));

        jLabelDevice.setBackground(new java.awt.Color(16, 99, 144));
        jLabelDevice.setFont(new java.awt.Font("Times New Roman", 1, 15)); // NOI18N
        jLabelDevice.setForeground(new java.awt.Color(255, 255, 255));
        jLabelDevice.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelDevice.setText("Quản lý thiết bị");

        javax.swing.GroupLayout panelDeviceLayout = new javax.swing.GroupLayout(panelDevice);
        panelDevice.setLayout(panelDeviceLayout);
        panelDeviceLayout.setHorizontalGroup(
            panelDeviceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelDeviceLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelDevice, javax.swing.GroupLayout.DEFAULT_SIZE, 173, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelDeviceLayout.setVerticalGroup(
            panelDeviceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDeviceLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelDevice, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                .addContainerGap())
        );

        panelViolation.setBackground(new java.awt.Color(36, 140, 190));
        panelViolation.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        panelViolation.setForeground(new java.awt.Color(255, 255, 255));
        panelViolation.setPreferredSize(new java.awt.Dimension(187, 65));

        jLabelViolation.setBackground(new java.awt.Color(16, 99, 144));
        jLabelViolation.setFont(new java.awt.Font("Times New Roman", 1, 15)); // NOI18N
        jLabelViolation.setForeground(new java.awt.Color(255, 255, 255));
        jLabelViolation.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelViolation.setText("Xử lý vi phạm");

        javax.swing.GroupLayout panelViolationLayout = new javax.swing.GroupLayout(panelViolation);
        panelViolation.setLayout(panelViolationLayout);
        panelViolationLayout.setHorizontalGroup(
            panelViolationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelViolationLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelViolation, javax.swing.GroupLayout.DEFAULT_SIZE, 173, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelViolationLayout.setVerticalGroup(
            panelViolationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelViolationLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelViolation, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                .addContainerGap())
        );

        panelAnalytics.setBackground(new java.awt.Color(36, 140, 190));
        panelAnalytics.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        panelAnalytics.setForeground(new java.awt.Color(255, 255, 255));
        panelAnalytics.setPreferredSize(new java.awt.Dimension(187, 65));

        jLabelAnalytics.setBackground(new java.awt.Color(16, 99, 144));
        jLabelAnalytics.setFont(new java.awt.Font("Times New Roman", 1, 15)); // NOI18N
        jLabelAnalytics.setForeground(new java.awt.Color(255, 255, 255));
        jLabelAnalytics.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelAnalytics.setText("Thống kê");

        javax.swing.GroupLayout panelAnalyticsLayout = new javax.swing.GroupLayout(panelAnalytics);
        panelAnalytics.setLayout(panelAnalyticsLayout);
        panelAnalyticsLayout.setHorizontalGroup(
            panelAnalyticsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAnalyticsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelAnalytics, javax.swing.GroupLayout.DEFAULT_SIZE, 173, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelAnalyticsLayout.setVerticalGroup(
            panelAnalyticsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAnalyticsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelAnalytics, javax.swing.GroupLayout.DEFAULT_SIZE, 51, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout panelMenuLayout = new javax.swing.GroupLayout(panelMenu);
        panelMenu.setLayout(panelMenuLayout);
        panelMenuLayout.setHorizontalGroup(
            panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMenuLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelMenber, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panelViolation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panelDevice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panelAnalytics, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(7, Short.MAX_VALUE))
        );

        panelMenuLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {panelAnalytics, panelDevice, panelMenber, panelViolation});

        panelMenuLayout.setVerticalGroup(
            panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMenuLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(panelMenber, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(55, 55, 55)
                .addComponent(panelDevice, javax.swing.GroupLayout.DEFAULT_SIZE, 64, Short.MAX_VALUE)
                .addGap(55, 55, 55)
                .addComponent(panelViolation, javax.swing.GroupLayout.DEFAULT_SIZE, 64, Short.MAX_VALUE)
                .addGap(55, 55, 55)
                .addComponent(panelAnalytics, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(38, 38, 38))
        );

        jPanel4.setBackground(new java.awt.Color(36, 140, 190));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 63, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jpnViewLayout = new javax.swing.GroupLayout(jpnView);
        jpnView.setLayout(jpnViewLayout);
        jpnViewLayout.setHorizontalGroup(
            jpnViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnViewLayout.createSequentialGroup()
                .addComponent(panelMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jpnViewLayout.setVerticalGroup(
            jpnViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpnViewLayout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpnViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelMenu, javax.swing.GroupLayout.DEFAULT_SIZE, 497, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 497, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jpnView, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jpnView, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    private void TrinhDieuKhien() {
        Controller controller = new Controller(jpnView);
        List<BeanRegistry> listItem = new ArrayList<>();

        // listItem.add(new DanhMucBean("TrangChinh",jpnTrangChu,jlbTrangChu));
        // listItem.add(new
        // DanhMucBean("PhieuNhapHang",panelPhieuNhap,jLabelPhieuNhap));
        listItem.add(new BeanRegistry("Course", panelMenber, jLabelMenber));
        listItem.add(new BeanRegistry("Person", panelDevice, jLabelDevice));
        listItem.add(new BeanRegistry("Department", panelViolation, jLabelViolation));
        listItem.add(new BeanRegistry("StudentGrade", panelAnalytics, jLabelAnalytics));
        controller.setEvent(listItem);
        try {
            controller.setView(panelMenber, jLabelMenber);
        } catch (SQLException ex) {
            Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        

    }
    //
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabelAnalytics;
    private javax.swing.JLabel jLabelDevice;
    private javax.swing.JLabel jLabelMenber;
    private javax.swing.JLabel jLabelViolation;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jpnView;
    private javax.swing.JPanel panelAnalytics;
    private javax.swing.JPanel panelDevice;
    private javax.swing.JPanel panelMenber;
    private javax.swing.JPanel panelMenu;
    private javax.swing.JPanel panelViolation;
    // End of variables declaration//GEN-END:variables
}
